[package]
name = "rust_os"
version = "0.1.0"
edition = "2018"
author = ["Leo Kim <leobkkim@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.23"
volatile = "0.2.6"
